/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/home/apartamento.glb --typescript 
Author: SrMonteiro (https://sketchfab.com/crispimrafael)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apartamento-77e965e2d3244bd58c476ca96baf387e
Title: Apartamento
*/
"use client";
import React, { Suspense } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

useGLTF.preload("/apartamento.glb");

export function Model(props) {
  const { nodes, materials } = useGLTF("/apartamento.glb");
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={1.111}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group
              position={[-188.092, 103, -689.156]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            >
              <mesh
                geometry={nodes["2_Handles_4_Metal_Chrome_0"].geometry}
                material={materials["4_Metal_Chrome"]}
                position={[-10.244, 0, 0]}
              />
            </group>
            <group
              position={[42.144, 46, -515.541]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            >
              <group position={[0, 0.75, 5]}>
                <mesh
                  geometry={nodes["4_TV_4_TV_Black+Logo_Samsung_0"].geometry}
                  material={materials["4_TV_BlackLogo_Samsung"]}
                />
                <mesh
                  geometry={nodes["4_TV_4_Metal_Black_Glossy_0"].geometry}
                  material={materials["4_Metal_Black_Glossy"]}
                />
              </group>
            </group>
            <group
              position={[-248.35, 0, -410.339]}
              rotation={[-Math.PI / 2, 0, Math.PI / 9]}
            >
              <group
                position={[44.206, -4.169, 151.174]}
                rotation={[-Math.PI, Math.PI / 9, -Math.PI]}
              >
                <mesh
                  geometry={
                    nodes["4_Lamp_Pedestal_4_Metal_Black_Glossy_0"].geometry
                  }
                  material={materials["4_Metal_Black_Glossy"]}
                />
                <mesh
                  geometry={
                    nodes["4_Lamp_Pedestal_4_Light_Material_0"].geometry
                  }
                  material={materials["4_Light_Material"]}
                />
                <mesh
                  geometry={nodes["4_Lamp_Pedestal_4_Metal_Chrome_0"].geometry}
                  material={materials["4_Metal_Chrome"]}
                />
              </group>
            </group>
            <group
              position={[394.697, 60, -346.511]}
              rotation={[-Math.PI / 2, 0, 2.356]}
            >
              <group
                position={[44.206, -4.169, 151.174]}
                rotation={[-Math.PI, Math.PI / 9, -Math.PI]}
              >
                <mesh
                  geometry={
                    nodes["4_Bedroom_Abajour_4_Metal_Black_Glossy_0"].geometry
                  }
                  material={materials["4_Metal_Black_Glossy"]}
                />
                <mesh
                  geometry={
                    nodes["4_Bedroom_Abajour_4_Light_Material_0"].geometry
                  }
                  material={materials["4_Light_Material"]}
                />
                <mesh
                  geometry={
                    nodes["4_Bedroom_Abajour_4_Metal_Chrome_0"].geometry
                  }
                  material={materials["4_Metal_Chrome"]}
                />
              </group>
            </group>
            <group
              position={[394.697, 60, -663.857]}
              rotation={[-Math.PI / 2, 0, -2.356]}
            >
              <group
                position={[44.206, -4.169, 151.174]}
                rotation={[-Math.PI, Math.PI / 9, -Math.PI]}
              >
                <mesh
                  geometry={
                    nodes["4_Bedroom_Abajour_4_Metal_Black_Glossy_0_1"].geometry
                  }
                  material={materials["4_Metal_Black_Glossy"]}
                />
                <mesh
                  geometry={
                    nodes["4_Bedroom_Abajour_4_Light_Material_0_1"].geometry
                  }
                  material={materials["4_Light_Material"]}
                />
                <mesh
                  geometry={
                    nodes["4_Bedroom_Abajour_4_Metal_Chrome_0_1"].geometry
                  }
                  material={materials["4_Metal_Chrome"]}
                />
              </group>
            </group>
            <group
              position={[-104.742, 0, 69.533]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes["4_Kitchen_Freezer_4_Metal_Stainless_0"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={
                  nodes["4_Kitchen_Freezer_4_Metal_Grey_Rough_0"].geometry
                }
                material={materials["4_Metal_Grey_Rough"]}
              />
              <mesh
                geometry={
                  nodes["4_Kitchen_Freezer_4_Metal_Black_Rough_0"].geometry
                }
                material={materials["4_Metal_Black_Rough"]}
              />
            </group>
            <group
              position={[-255.742, 140, -48.092]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes["4_Kitchen_Microwave_4_Metal_Grey_Rough_0"].geometry
                }
                material={materials["4_Metal_Grey_Rough"]}
              />
              <mesh
                geometry={
                  nodes["4_Kitchen_Microwave_4_Metal_Chrome_0"].geometry
                }
                material={materials["4_Metal_Chrome"]}
              />
              <mesh
                geometry={
                  nodes["4_Kitchen_Microwave_4_Metal_Stainless_0"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
            </group>
            <group
              position={[-243.992, 12, -205.342]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes["4_Kitchen_WashMachine_4_Metal_Stainless_0"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={
                  nodes["4_Kitchen_WashMachine_4_Metal_Grey_Rough_0"].geometry
                }
                material={materials["4_Metal_Grey_Rough"]}
              />
            </group>
            <group
              position={[382.996, 0, 27.998]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes["4_Bathroom_Trash_Can_4_Metal_Chrome_0"].geometry
                }
                material={materials["4_Metal_Chrome"]}
                position={[11.5, -2.5, 0]}
              />
            </group>
            <group
              position={[409.496, 100, -47.747]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes["4_BathRoom_Mirror__4_Metal_Black_Rough_0"].geometry
                }
                material={materials["4_Metal_Black_Rough"]}
              />
              <mesh
                geometry={nodes["4_BathRoom_Mirror__4_Mirror_0"].geometry}
                material={materials["4_Mirror"]}
              />
            </group>
            <group position={[29.964, 82.508, -637.316]} scale={0.8}>
              <mesh
                geometry={
                  nodes["5_Vegetation_Plant_5_Vegetation_Palm_0"].geometry
                }
                material={materials["5_Vegetation_Palm"]}
                position={[-14.46, -5.251, -1.805]}
              />
            </group>
            <group
              position={[412.996, 120, 45.397]}
              rotation={[0, -Math.PI / 2, 0]}
            >
              <mesh
                geometry={nodes["4_Bathroom_Shelf_4_Metal_Chrome_0"].geometry}
                material={materials["4_Metal_Chrome"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Shelf_4_Glass_0"].geometry}
                material={materials["4_Glass"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Shelf_4_Fabric_Towel_0"].geometry}
                material={materials["4_Fabric_Towel"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Shelf_4_Ceramic_0"].geometry}
                material={materials["4_Ceramic"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Shelf_4_Bathroom_Wood_0"].geometry}
                material={materials["4_Bathroom_Wood"]}
              />
            </group>
            <group
              position={[202.815, 100, 106.974]}
              rotation={[Math.PI, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes["4_Bathroom_Shelf_4_Metal_Chrome_0_1"].geometry}
                material={materials["4_Metal_Chrome"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Shelf_4_Glass_0_1"].geometry}
                material={materials["4_Glass"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Shelf_4_Ceramic_0_1"].geometry}
                material={materials["4_Ceramic"]}
              />
              <mesh
                geometry={
                  nodes["4_Bathroom_Shelf_4_Plastic_Cream_Shower_0"].geometry
                }
                material={materials["4_Plastic_Cream_Shower"]}
              />
            </group>
            <group
              position={[221.828, 10, 48.391]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes["4_Bathroom_Box_4_Metal_Chrome_0"].geometry}
                material={materials["4_Metal_Chrome"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Box_4_Glass_0"].geometry}
                material={materials["4_Glass"]}
              />
            </group>
            <group
              position={[376.016, 0, 62.211]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={0.043}
            >
              <mesh
                geometry={nodes["4_Bathroom_Flush_4_Metal_Chrome_0"].geometry}
                material={materials["4_Metal_Chrome"]}
                position={[-457.2, -850.9, 0]}
              />
            </group>
            <group
              position={[-241.992, 140.5, -225.279]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes["4_Kitchen_Handle_06_4_Metal_Gold_0"].geometry}
                material={materials["4_Metal_Gold"]}
                position={[2, 0, 0]}
              />
            </group>
            <group
              position={[-213.492, 49, -48.092]}
              rotation={[0, Math.PI / 2, 0]}
            >
              <mesh
                geometry={
                  nodes["4_Kitchen_Oven_4_Metal_Black_Glossy_0"].geometry
                }
                material={materials["4_Metal_Black_Glossy"]}
              />
              <mesh
                geometry={nodes["4_Kitchen_Oven_4_Metal_Stainless_0"].geometry}
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["4_Kitchen_Oven_4_Glass_0"].geometry}
                material={materials["4_Glass"]}
              />
            </group>
            <group
              position={[88.295, 265, -2.142]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.5}
            >
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Metal_Stainless_0"].geometry}
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Light_Material_0"].geometry}
                material={materials["4_Light_Material"]}
              />
            </group>
            <group
              position={[-251.492, 265, -329.326]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.5}
            >
              <mesh
                geometry={
                  nodes["6_HQI_Pictures_4_Metal_Stainless_0_1"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Light_Material_0_1"].geometry}
                material={materials["4_Light_Material"]}
              />
            </group>
            <group
              position={[-251.492, 265, -468.16]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.5}
            >
              <mesh
                geometry={
                  nodes["6_HQI_Pictures_4_Metal_Stainless_0_2"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Light_Material_0_2"].geometry}
                material={materials["4_Light_Material"]}
              />
            </group>
            <group
              position={[-251.492, 265, -527.331]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.5}
            >
              <mesh
                geometry={
                  nodes["6_HQI_Pictures_4_Metal_Stainless_0_3"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Light_Material_0_3"].geometry}
                material={materials["4_Light_Material"]}
              />
            </group>
            <group
              position={[-251.492, 265, -587.331]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.5}
            >
              <mesh
                geometry={
                  nodes["6_HQI_Pictures_4_Metal_Stainless_0_4"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Light_Material_0_4"].geometry}
                material={materials["4_Light_Material"]}
              />
            </group>
            <group
              position={[391.714, 265, -545.162]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.5}
            >
              <mesh
                geometry={
                  nodes["6_HQI_Pictures_4_Metal_Stainless_0_5"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Light_Material_0_5"].geometry}
                material={materials["4_Light_Material"]}
              />
            </group>
            <group
              position={[391.714, 265, -463.241]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.5}
            >
              <mesh
                geometry={
                  nodes["6_HQI_Pictures_4_Metal_Stainless_0_6"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Light_Material_0_6"].geometry}
                material={materials["4_Light_Material"]}
              />
            </group>
            <group
              position={[285.496, 265, -212.653]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.5}
            >
              <mesh
                geometry={
                  nodes["6_HQI_Pictures_4_Metal_Stainless_0_7"].geometry
                }
                material={materials["4_Metal_Stainless"]}
              />
              <mesh
                geometry={nodes["6_HQI_Pictures_4_Light_Material_0_7"].geometry}
                material={materials["4_Light_Material"]}
              />
            </group>
            <group
              position={[-276.492, 0, 107.533]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <group
                position={[195.965, 282.612, 0]}
                rotation={[0, 0, Math.PI / 4]}
              >
                <mesh
                  geometry={nodes["3_Kitchen_Material_#129_0"].geometry}
                  material={materials.Material_129}
                />
                <mesh
                  geometry={nodes["3_Kitchen_Material_#129_0_1"].geometry}
                  material={materials.Material_129}
                />
                <mesh
                  geometry={nodes["3_Kitchen_Material_#129_0_2"].geometry}
                  material={materials.Material_129}
                />
                <mesh
                  geometry={nodes["3_Kitchen_Material_#129_0_3"].geometry}
                  material={materials.Material_129}
                />
                <mesh
                  geometry={nodes["3_Kitchen_Material_#129_0_4"].geometry}
                  material={materials.Material_129}
                />
                <mesh
                  geometry={nodes["3_Kitchen_Material_#129_0_5"].geometry}
                  material={materials.Material_129}
                />
              </group>
            </group>
            <group
              position={[-234.992, 91.5, -27.095]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={
                  nodes["4_Kitchen_Cooktop_4_Metal_Black_Glossy_0"].geometry
                }
                material={materials["4_Metal_Black_Glossy"]}
              />
              <mesh
                geometry={
                  nodes["4_Kitchen_Cooktop_4_Metal_White_Glossy_0"].geometry
                }
                material={materials["4_Metal_White_Glossy"]}
              />
            </group>
            <group
              position={[412.746, 46.5, 26.857]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes["4_Bathroom_Paper_4_Metal_Chrome_0"].geometry}
                material={materials["4_Metal_Chrome"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Paper_4_Ceramic_0"].geometry}
                material={materials["4_Ceramic"]}
              />
            </group>
            <group
              position={[281.662, 148.5, 106.724]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes["4_Bathroom_Towel_4_Metal_Chrome_0"].geometry}
                material={materials["4_Metal_Chrome"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Towel_4_Fabric_Towel_0"].geometry}
                material={materials["4_Fabric_Towel"]}
              />
            </group>
            <group
              position={[397.53, 98.84, -96.132]}
              rotation={[-Math.PI / 2, 0, -2.274]}
            >
              <mesh
                geometry={nodes["4_Bathroom_Soap_4_Metal_Chrome_0"].geometry}
                material={materials["4_Metal_Chrome"]}
              />
              <mesh
                geometry={nodes["4_Bathroom_Soap_4_Ceramic_0"].geometry}
                material={materials["4_Ceramic"]}
              />
            </group>
            <group
              position={[-116.062, 72, -139.543]}
              rotation={[Math.PI, Math.PI / 4, -Math.PI]}
              scale={[0.027, 0.05, 0.027]}
            >
              <group position={[-1772.143, 20.085, 2268.883]}>
                <mesh
                  geometry={nodes["7_Dinner_4_Ceramic_0"].geometry}
                  material={materials["4_Ceramic"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Metal_Gold_0"].geometry}
                  material={materials["4_Metal_Gold"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Metal_Chrome_0"].geometry}
                  material={materials["4_Metal_Chrome"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Glass_0"].geometry}
                  material={materials["4_Glass"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_7_Dinner_0"].geometry}
                  material={materials["7_Dinner"]}
                />
              </group>
            </group>
            <group
              position={[90.163, 168.75, -472.914]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={0.25}
            >
              <mesh
                geometry={nodes["7_Books_21_Material_#136_0"].geometry}
                material={materials.Material_136}
                position={[-226.119, -2.092, 0]}
              />
            </group>
            <group
              position={[82.564, 117.5, -649.772]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={0.5}
            >
              <mesh
                geometry={nodes["7_Vase_01_Material_#138_0"].geometry}
                material={materials.Material_138}
                position={[40.921, 30.281, 0]}
              />
            </group>
            <group
              position={[85.966, 117.5, -633.302]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={0.5}
            >
              <mesh
                geometry={nodes["7_Vase_00_Material_#138_0"].geometry}
                material={materials.Material_138}
                position={[-5.333, 30.12, 0]}
              />
            </group>
            <group
              position={[-105.685, 35.5, -521.803]}
              rotation={[0, -0.984, 0]}
              scale={0.8}
            >
              <mesh
                geometry={nodes["7_Magazines_7_Magazines_0"].geometry}
                material={materials["7_Magazines"]}
                position={[0, 0.173, 0]}
              />
            </group>
            <group
              position={[-44.992, 72, -139.543]}
              rotation={[Math.PI, -Math.PI / 4, Math.PI]}
              scale={[0.027, 0.05, 0.027]}
            >
              <group position={[-1772.143, 20.085, 2268.883]}>
                <mesh
                  geometry={nodes["7_Dinner_4_Ceramic_0_1"].geometry}
                  material={materials["4_Ceramic"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Metal_Gold_0_1"].geometry}
                  material={materials["4_Metal_Gold"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Metal_Chrome_0_1"].geometry}
                  material={materials["4_Metal_Chrome"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Glass_0_1"].geometry}
                  material={materials["4_Glass"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_7_Dinner_0_1"].geometry}
                  material={materials["7_Dinner"]}
                />
              </group>
            </group>
            <group
              position={[-44.992, 72, -210.613]}
              rotation={[0, -Math.PI / 4, 0]}
              scale={[0.027, 0.05, 0.027]}
            >
              <group position={[-1772.143, 20.085, 2268.883]}>
                <mesh
                  geometry={nodes["7_Dinner_4_Ceramic_0_2"].geometry}
                  material={materials["4_Ceramic"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Metal_Gold_0_2"].geometry}
                  material={materials["4_Metal_Gold"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Metal_Chrome_0_2"].geometry}
                  material={materials["4_Metal_Chrome"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Glass_0_2"].geometry}
                  material={materials["4_Glass"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_7_Dinner_0_2"].geometry}
                  material={materials["7_Dinner"]}
                />
              </group>
            </group>
            <group
              position={[-116.062, 72, -210.613]}
              rotation={[0, Math.PI / 4, 0]}
              scale={[0.027, 0.05, 0.027]}
            >
              <group position={[-1772.142, 20.078, 2268.883]}>
                <mesh
                  geometry={nodes["7_Dinner_4_Ceramic_0_3"].geometry}
                  material={materials["4_Ceramic"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Metal_Gold_0_3"].geometry}
                  material={materials["4_Metal_Gold"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Metal_Chrome_0_3"].geometry}
                  material={materials["4_Metal_Chrome"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_4_Glass_0_3"].geometry}
                  material={materials["4_Glass"]}
                />
                <mesh
                  geometry={nodes["7_Dinner_7_Dinner_0_3"].geometry}
                  material={materials["7_Dinner"]}
                />
              </group>
            </group>
            <group
              position={[93.839, 168.75, -539.957]}
              rotation={[0, 1.341, 0]}
              scale={0.018}
            >
              <mesh
                geometry={nodes["7_Statuette_4_Metal_Black_Glossy_0"].geometry}
                material={materials["4_Metal_Black_Glossy"]}
                position={[42.159, 52.276, 99.324]}
              />
            </group>
            <group
              position={[-258.186, 92, -69.27]}
              rotation={[0, Math.PI / 2, 0]}
              scale={0.1}
            >
              <mesh
                geometry={nodes["7_Teapot_4_Metal_Chrome_0"].geometry}
                material={materials["4_Metal_Chrome"]}
              />
              <mesh
                geometry={nodes["7_Teapot_4_Metal_Black_Rough_0"].geometry}
                material={materials["4_Metal_Black_Rough"]}
              />
            </group>
            <group
              position={[94.738, 136.502, -595.764]}
              rotation={[0.176, 0, -Math.PI]}
              scale={22.789}
            >
              <mesh
                geometry={nodes["7_Books_01_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[5.085, 1.417, 0]}
              />
            </group>
            <group
              position={[90.651, 128.263, -593.122]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={35}
            >
              <mesh
                geometry={nodes["7_Books_02_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[4.085, 1.417, 0]}
              />
            </group>
            <group
              position={[85.269, 65.807, -465.458]}
              rotation={[-2.96, 0, -Math.PI]}
              scale={28}
            >
              <mesh
                geometry={nodes["7_Books_06_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[1.115, 1.407, 0]}
              />
            </group>
            <group
              position={[85.269, 65.849, -462.196]}
              rotation={[-2.966, 0, -Math.PI]}
              scale={28}
            >
              <mesh
                geometry={nodes["7_Books_04_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[3.115, 1.417, 0]}
              />
            </group>
            <group
              position={[84.722, 66.861, -495.277]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={29.09}
            >
              <mesh
                geometry={nodes["7_Books_05_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[2.115, 1.417, 0]}
              />
            </group>
            <group
              position={[90.164, 67.366, -542.849]}
              rotation={[-0.456, 0.88, 0.361]}
              scale={28.198}
            >
              <mesh
                geometry={nodes["7_Books_10_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[-0.79, 1.417, 0]}
              />
            </group>
            <group
              position={[90.708, 66.086, -548.986]}
              rotation={[-0.374, 0.675, 0.24]}
              scale={27.267}
            >
              <mesh
                geometry={nodes["7_Books_11_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[-1.672, 1.417, 0]}
              />
            </group>
            <group
              position={[85.269, 65.849, -468.433]}
              rotation={[-2.941, 0, -Math.PI]}
              scale={28}
            >
              <mesh
                geometry={nodes["7_Books_09_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[0.21, 1.418, 0]}
              />
            </group>
            <group
              position={[94.738, 136.157, -605.522]}
              rotation={[0.23, 0, -Math.PI]}
              scale={22.789}
            >
              <mesh
                geometry={nodes["7_Books_00_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[6.085, 1.418, 0]}
              />
            </group>
            <group
              position={[84.722, 73.061, -495.277]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={29.09}
            >
              <mesh
                geometry={nodes["7_Books_20_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[6.083, -0.612, 0]}
              />
            </group>
            <group
              position={[90.651, 116.612, -593.122]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={35}
            >
              <mesh
                geometry={nodes["7_Books_19_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[-2.917, -0.611, 0]}
              />
            </group>
            <group
              position={[94.739, 137.038, -598.664]}
              rotation={[0.176, 0, -Math.PI]}
              scale={22.789}
            >
              <mesh
                geometry={nodes["7_Books_08_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[-1.913, -0.574, 0]}
              />
            </group>
            <group
              position={[85.269, 65.849, -458.806]}
              rotation={[-2.963, 0, -Math.PI]}
              scale={28}
            >
              <mesh
                geometry={nodes["7_Books_18_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[-4.802, -0.612, 0]}
              />
            </group>
            <group
              position={[94.739, 135.282, -597.354]}
              rotation={[0.176, 0, -Math.PI]}
              scale={22.789}
            >
              <mesh
                geometry={nodes["7_Books_17_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[-3.916, -0.612, 0]}
              />
            </group>
            <group
              position={[94.739, 136.285, -603.109]}
              rotation={[0.176, 0, -Math.PI]}
              scale={22.789}
            >
              <mesh
                geometry={nodes["7_Books_16_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[1.083, -0.613, 0]}
              />
            </group>
            <group
              position={[90.651, 120.51, -594.414]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={35}
            >
              <mesh
                geometry={nodes["7_Books_15_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[2.086, -0.539, 0]}
              />
            </group>
            <group
              position={[84.722, 69.81, -495.277]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={29.09}
            >
              <mesh
                geometry={nodes["7_Books_07_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[-0.917, -0.613, 0]}
              />
            </group>
            <group
              position={[94.739, 135.137, -600.909]}
              rotation={[0.176, 0, -Math.PI]}
              scale={22.789}
            >
              <mesh
                geometry={nodes["7_Books_14_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[0.083, -0.623, 0]}
              />
            </group>
            <group
              position={[90.651, 123.162, -593.122]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
              scale={35}
            >
              <mesh
                geometry={nodes["7_Books_03_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[3.083, -0.612, 0]}
              />
            </group>
            <group
              position={[85.269, 65.848, -455.477]}
              rotation={[-2.959, 0, -Math.PI]}
              scale={28}
            >
              <mesh
                geometry={nodes["7_Books_13_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[4.083, -0.613, 0]}
              />
            </group>
            <group
              position={[84.722, 65.61, -494.68]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={29.09}
            >
              <mesh
                geometry={nodes["7_Books_12_Material_#137_0"].geometry}
                material={materials.Material_137}
                position={[5.087, -0.653, 0]}
              />
            </group>
            <group
              position={[-260.842, 91, 28.75]}
              rotation={[-Math.PI / 2, 0, 2.356]}
              scale={0.001}
            >
              <group position={[-0.002, 2077.638, -3.128]}>
                <mesh
                  geometry={nodes["7_Knifes_7_Knifes_0"].geometry}
                  material={materials["7_Knifes"]}
                />
                <mesh
                  geometry={nodes["7_Knifes_4_Metal_Chrome_0"].geometry}
                  material={materials["4_Metal_Chrome"]}
                />
                <mesh
                  geometry={nodes["7_Knifes_4_Metal_Black_Rough_0"].geometry}
                  material={materials["4_Metal_Black_Rough"]}
                />
              </group>
            </group>
            <group
              position={[-241.994, 91, -210.188]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.6}
            >
              <mesh
                geometry={
                  nodes["7_Vegetation_Green_Plant_4_Ceramic_0"].geometry
                }
                material={materials["4_Ceramic"]}
              />
              <mesh
                geometry={
                  nodes["7_Vegetation_Green_Plant_4_Metal_Black_Rough_0"]
                    .geometry
                }
                material={materials["4_Metal_Black_Rough"]}
              />
              <mesh
                geometry={
                  nodes["7_Vegetation_Green_Plant_7_Vegetation_Green_Plant_0"]
                    .geometry
                }
                material={materials["7_Vegetation_Green_Plant"]}
              />
            </group>
            <group
              position={[-79.867, 72.087, -174.415]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.6}
            >
              <mesh
                geometry={nodes["7_Vegetation_Red_Plant_4_Ceramic_0"].geometry}
                material={materials["4_Ceramic"]}
              />
              <mesh
                geometry={
                  nodes["7_Vegetation_Red_Plant_4_Metal_Black_Rough_0"].geometry
                }
                material={materials["4_Metal_Black_Rough"]}
              />
              <mesh
                geometry={
                  nodes["7_Vegetation_Red_Plant_7_Vegetation_Red_Plant_0"]
                    .geometry
                }
                material={materials["7_Vegetation_Red_Plant"]}
              />
            </group>
            <mesh
              geometry={nodes["1_Structure_Material_#122_0"].geometry}
              material={materials.Material_122}
              position={[-75.227, 0, -255.302]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["2_Door_Windows_Material_#123_0"].geometry}
              material={materials.Material_123}
              position={[58.259, 0, -430.606]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes["2_Railing_4_Metal_Black_Railing_0"].geometry}
              material={materials["4_Metal_Black_Railing"]}
              position={[-105.807, -3, -894.386]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["3_Living_Room_Material_#130_0"].geometry}
              material={materials.Material_130}
              position={[-97.503, 0.2, -523.939]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Bathroom_Grid_4_Metal_Shower_0"].geometry}
              material={materials["4_Metal_Shower"]}
              position={[172.861, 2, 33.91]}
              rotation={[-Math.PI / 2, 0, Math.PI]}
            />
            <mesh
              geometry={nodes["3_Closet_Material_#133_0"].geometry}
              material={materials.Material_133}
              position={[209.062, 0, -213.096]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["3_Picture_Material_#131_0"].geometry}
              material={materials.Material_131}
              position={[112.295, 110, -2.142]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Bathroom_Faucet_4_Metal_Chrome_0"].geometry}
              material={materials["4_Metal_Chrome"]}
              position={[394.949, 98, -47.746]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Bathroom_Shower_4_Metal_Shower_0"].geometry}
              material={materials["4_Metal_Shower"]}
              position={[173.411, 218.378, 34.308]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Living_Room_Metal_4_Metal_Gold_0"].geometry}
              material={materials["4_Metal_Gold"]}
              position={[-74.212, 20, -531.605]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              geometry={nodes["3_Bathroom_Material_#124_0"].geometry}
              material={materials.Material_124}
              position={[382.996, 15, -47.747]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Kithchen_Faucet_4_Metal_Chrome_0"].geometry}
              material={materials["4_Metal_Chrome"]}
              position={[-266.992, 91, -126.698]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Kitchen_Sink_4_Metal_Stainless_0"].geometry}
              material={materials["4_Metal_Stainless"]}
              position={[-241.492, 89, -126.842]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["3_Bedroom_Material_#126_0"].geometry}
              material={materials.Material_126}
              position={[300.496, 24, -504.853]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Closet_Mirror_4_Mirror_0"].geometry}
              material={materials["4_Mirror"]}
              position={[209.062, 0, -213.096]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Glass_4_Glass_0"].geometry}
              material={materials["4_Glass"]}
              position={[-2.728, 49, -706.162]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Glass_4_Glass_0_1"].geometry}
              material={materials["4_Glass"]}
              position={[313.893, 76, -701.957]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Glass_4_Glass_0_2"].geometry}
              material={materials["4_Glass"]}
              position={[236.893, 76, -704.957]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["4_Glass_4_Glass_0_3"].geometry}
              material={materials["4_Glass"]}
              position={[-140.149, 31.5, -749.111]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes["7_Sugar_Pot_Material_#142_0"].geometry}
              material={materials.Material_142}
              position={[-268.529, 91, 100.599]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes["7_Coffee_Pot_Material_#141_0"].geometry}
              material={materials.Material_141}
              position={[-238.936, 91, 101.781]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes["7_Chocolate_Pot_Material_#143_0"].geometry}
              material={materials.Material_143}
              position={[-253.51, 91, 100.748]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes["7_Tablet_Material_#139_0"].geometry}
              material={materials.Material_139}
              position={[368.359, 60, -632.894]}
              rotation={[-Math.PI / 2, 0, 2.299]}
            />
            <mesh
              geometry={nodes["7_Coffee_machine_Material_#140_0"].geometry}
              material={materials.Material_140}
              position={[-178.32, 91, 89.944]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={0.1}
            />
            <mesh
              geometry={nodes["7_Meat_Board_Material_#144_0"].geometry}
              material={materials.Material_144}
              position={[-274.791, 106.834, 10.561]}
              rotation={[-Math.PI / 2, 1.472, Math.PI / 2]}
              scale={0.8}
            />
            <mesh
              geometry={nodes["7_Cup_4_Ceramic_0"].geometry}
              material={materials["4_Ceramic"]}
              position={[-198.439, 91.083, 67.189]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <mesh
              geometry={nodes["7_Cup_4_Ceramic_0_1"].geometry}
              material={materials["4_Ceramic"]}
              position={[-211.552, 91.083, 67.189]}
              rotation={[0, -Math.PI / 2, 0]}
            />
          </group>
        </group>
      </group>
    </RigidBody>
  );
}
